"""クライアント別 計測ヘルスレポート（PDF）生成。

同梱の IPAexゴシック（fonts/ipaexg.ttf, IPAフォントライセンスv1.0）を使うため、
Windows / Mac / Linux いずれでも日本語PDFを出力できる。
"""
from __future__ import annotations
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

import clients as clients_mod
import health

ROOT = Path(__file__).parent
FONT_CANDIDATES = [
    ROOT / "fonts" / "ipaexg.ttf",          # 同梱（最優先・全OS共通）
    Path(r"C:\Windows\Fonts\meiryo.ttc"),
    Path(r"C:\Windows\Fonts\YuGothM.ttc"),
]

GREEN = (46, 125, 50)
GREEN_LIGHT = (232, 245, 233)
GRAY = (90, 106, 90)
GRADE_COLORS = {"A": (67, 160, 71), "B": (139, 195, 74), "C": (255, 179, 0),
                "D": (251, 140, 0), "F": (229, 57, 53)}


class ReportPDF(FPDF):
    FONT = "jp"

    def __init__(self, client_name: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.client_name = client_name
        self._font_ok = False
        for p in FONT_CANDIDATES:
            if p.exists():
                self.add_font(self.FONT, fname=str(p))
                self._font_ok = True
                break
        if not self._font_ok:
            self.FONT = "helvetica"
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        self.set_font(self.FONT, size=9)
        self.set_text_color(*GRAY)
        self.cell(0, 6, f"{self.client_name} 計測ヘルスレポート", align="L")
        self.cell(0, 6, datetime.now().strftime("%Y-%m-%d"), align="R",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*GREEN)
        self.set_line_width(0.4)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font(self.FONT, size=8)
        self.set_text_color(150, 160, 150)
        self.cell(0, 6, f"Generated by Analytics Inventory — {self.page_no()}", align="C")

    # ---- helpers ----
    def h1(self, text):
        self.set_font(self.FONT, size=17)
        self.set_text_color(27, 94, 32)
        self.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def h2(self, text):
        self.ln(2)
        self.set_font(self.FONT, size=12)
        self.set_text_color(27, 94, 32)
        self.set_fill_color(*GREEN_LIGHT)
        self.cell(0, 8, "  " + text, fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def para(self, text, size=9, color=(31, 42, 31)):
        self.set_font(self.FONT, size=size)
        self.set_text_color(*color)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def table(self, headers, widths, rows, grade_col=None):
        self.set_font(self.FONT, size=8.5)
        self.set_fill_color(*GREEN_LIGHT)
        self.set_text_color(27, 94, 32)
        for h, w in zip(headers, widths):
            self.cell(w, 6.5, h, border="B", fill=True)
        self.ln()
        self.set_text_color(31, 42, 31)
        for i, row in enumerate(rows):
            if self.get_y() > 262:
                self.add_page()
                self.set_font(self.FONT, size=8.5)
                self.set_fill_color(*GREEN_LIGHT)
                self.set_text_color(27, 94, 32)
                for h, w in zip(headers, widths):
                    self.cell(w, 6.5, h, border="B", fill=True)
                self.ln()
                self.set_text_color(31, 42, 31)
            fill = i % 2 == 1
            self.set_fill_color(246, 250, 246)
            for j, (val, w) in enumerate(zip(row, widths)):
                txt = str(val)
                if len(txt) > 46:
                    txt = txt[:45] + "…"
                if grade_col is not None and j == grade_col and txt in GRADE_COLORS:
                    self.set_text_color(*GRADE_COLORS[txt])
                    self.set_font(self.FONT, size=8.5)
                    self.cell(w, 6, txt, border="B", fill=fill)
                    self.set_text_color(31, 42, 31)
                else:
                    self.cell(w, 6, txt, border="B", fill=fill)
            self.ln()
        if not rows:
            self.set_text_color(*GRAY)
            self.cell(0, 6, "（該当なし）", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(31, 42, 31)
        self.ln(2)


def _fmt(n):
    return f"{n:,}" if isinstance(n, (int, float)) and n is not None else "—"


def build_pdf(client: dict, inv: dict) -> bytes:
    ent = clients_mod.resolve_entities(client, inv)
    summary = clients_mod.summarize(client, inv)
    events = clients_mod.client_change_events(client, days=30, limit=40)

    pdf = ReportPDF(client.get("name", ""))
    pdf.add_page()

    pdf.h1(f"{client.get('name')} — 計測ヘルスレポート")
    gen = (inv.get("generated_at") or "")[:16].replace("T", " ")
    pdf.para(f"データ最終収集: {gen} ／ レポート生成: {datetime.now().strftime('%Y-%m-%d %H:%M')}", size=8.5, color=GRAY)
    if client.get("note"):
        pdf.para(f"メモ: {client['note']}", size=8.5, color=GRAY)

    # ---- サマリー ----
    pdf.h2("サマリー")
    pdf.table(
        ["対象", "件数", "平均スコア", "要対応（D/F・エラー）"],
        [50, 40, 45, 55],
        [
            ["GA4プロパティ", summary["ga4"]["n"], summary["ga4"]["avg"], summary["ga4"]["bad"]],
            ["GTMコンテナ", summary["gtm"]["n"], summary["gtm"]["avg"], summary["gtm"]["bad"]],
            ["Search Console", summary["sc"]["n"], summary["sc"]["avg"], summary["sc"]["bad"]],
        ])

    # ---- GA4 ----
    if ent["properties"]:
        pdf.h2("GA4プロパティ")
        rows = []
        for p in sorted(ent["properties"], key=lambda x: x.get("health_score") or 0):
            rows.append([
                p.get("display_name") or "", p.get("health_grade") or "", p.get("health_score") or 0,
                "計測中" if p.get("is_tracked") else "停止", p.get("key_event_count") or 0,
                _fmt(p.get("sessions_7d")), p.get("alert_count") or 0,
            ])
        pdf.table(["プロパティ", "評価", "スコア", "計測", "KE", "Sessions(7d)", "警告"],
                  [62, 12, 15, 18, 12, 30, 14], rows, grade_col=1)

    # ---- GTM ----
    if ent["containers"]:
        pdf.h2("GTMコンテナ")
        rows = []
        for c in sorted(ent["containers"], key=lambda x: x.get("health_score") or 0):
            rows.append([
                c.get("name") or "", c.get("health_grade") or "", c.get("health_score") or 0,
                c.get("tag_count") or 0,
                (c.get("_score_summary") or {}).get("ua_count", "—"),
                ", ".join(c.get("ga4_measurement_ids") or []) or "—",
                c.get("alert_count") or 0,
            ])
        pdf.table(["コンテナ", "評価", "スコア", "タグ", "UA系", "GA4連携", "警告"],
                  [52, 12, 15, 12, 12, 46, 14], rows, grade_col=1)

    # ---- SC ----
    if ent["sc_sites"]:
        pdf.h2("Search Console")
        rows = []
        for s in sorted(ent["sc_sites"], key=lambda x: x.get("health_score") or 0):
            rows.append([
                s.get("site_url") or "", s.get("health_grade") or "", s.get("health_score") or 0,
                _fmt(s.get("clicks_28d")), _fmt(s.get("impressions_28d")),
                f"{(s.get('ctr_28d') or 0) * 100:.2f}%", s.get("alert_count") or 0,
            ])
        pdf.table(["サイト", "評価", "スコア", "Click(28d)", "Imp(28d)", "CTR", "警告"],
                  [64, 12, 15, 24, 26, 16, 14], rows, grade_col=1)

    # ---- 変化ログ ----
    pdf.h2("直近30日の変化")
    sev_label = {"critical": "重大", "warn": "注意", "info": "情報"}
    rows = [[(e.get("detected_at") or "")[:10], sev_label.get(e.get("severity"), ""),
             e.get("entity_name") or "", e.get("message") or ""] for e in events]
    pdf.table(["検出日", "重要度", "対象", "内容"], [22, 14, 48, 106], rows)

    # ---- 要対応まとめ ----
    pdf.h2("要対応の詳細")
    any_alert = False
    for p in ent["properties"]:
        if p.get("ann_excluded"):
            continue
        alerts = [a for a in health.detect_alerts(p) if a["level"] in ("error", "warn")]
        if alerts:
            any_alert = True
            pdf.para(f"■ GA4: {p.get('display_name')}", size=9)
            for a in alerts:
                pdf.para(f"   ・[{ '重大' if a['level']=='error' else '注意' }] {a['message']}", size=8.5, color=GRAY)
    for c in ent["containers"]:
        if c.get("ann_excluded"):
            continue
        alerts = [a for a in (c.get("_alerts") or []) if a["level"] in ("error", "warn")]
        if alerts:
            any_alert = True
            pdf.para(f"■ GTM: {c.get('name')}", size=9)
            for a in alerts:
                pdf.para(f"   ・[{ '重大' if a['level']=='error' else '注意' }] {a['message']}", size=8.5, color=GRAY)
    for s in ent["sc_sites"]:
        if s.get("ann_excluded"):
            continue
        alerts = [a for a in (s.get("_alerts") or []) if a["level"] in ("error", "warn")]
        if alerts:
            any_alert = True
            pdf.para(f"■ SC: {s.get('site_url')}", size=9)
            for a in alerts:
                pdf.para(f"   ・[{ '重大' if a['level']=='error' else '注意' }] {a['message']}", size=8.5, color=GRAY)
    if not any_alert:
        pdf.para("要対応のアラートはありません。良好な状態です。", size=9)

    return bytes(pdf.output())
